# Generated by Django 4.0.2 on 2022-02-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_oda_app', '0003_alter_academician_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='academician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academician_payment', to='api_oda_app.academician', verbose_name='académicien'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academician_reason', to='api_oda_app.reason', verbose_name='motif'),
        ),
    ]
